---
title: "Automating Testing and Deployment"
author: "Tom Reilly"
date: '2024-03-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Foreword

This is a working document that will be added to and amended as methods are used and intriciacies of working with SCOTS and the OSE are dealt with.

## Testing

There are a wide array of options when it comes to testing packages in R. Two of the main ones looked at here are `tinytest` and `testthat`. They are very similar in their notation, both using expectations to drive their testing. `testthat` is the most popular testing package, but the benefit of using `tinytest` is that there are fewer package dependencies, something which is of benefit when working on the OSE where package downloads are often restricted. There will be more documentation out there on `testthat` so it may be preferable to use that as long as the dependencies don't hold you back. With the growing problems with working with R packages on the OSE investigating the `tinyverse`, which `tinytest` is a part of, will be worthwhile as it's main aim is to reduce package dependencies.

When developing a Shiny application it is easier to implement a testing suite when the app has been packaged. One simple method for creating a packaged Shiny app is to use the `golem` package. Within the setup you will be given the option to setup the relevant testing directories, this simplifies the process. `golem` uses the `testthat` in its testing setup.

#### Working with `tinytest`

`expect_equal(1 + 2, 3, info = "testing addition operator")`

We always compare two objects. The objects may be given directly as parameters or as statements to be executed. Their order does not really matter for the function result. However, it is better to keep it consistent. The messages assume that the first argument as an object under test (current object) and the second one as expected result (target object). In the code above we are testing whether `1 + 2` is equal to the second object, in this instance `3`. This obviously result in a passed test.

There are currently 16 different expectations that can be tested with `tinytest`.

#### Working with `testthat`

`testthat` works in the same way as `tinytest`, utilising expectations, like the one shown above. `testthat` offers a wider array of testing functions and expectations, details can be found here: https://testthat.r-lib.org/reference/. 

#### `shinytest`

Just to note another testing package; this one, as the name suggests, is specifically useful for Shiny apps. `shinytest` provides a simulation of a Shiny app that you can control in order to automate testing. `shinytest` uses a snapshot-based testing strategy: the first time it runs a set of tests for an application, it performs some scripted interactions with the app and takes one or more snapshots of the application’s state. Subsequent runs perform the same scripted interactions then compare the results; you’ll get an error if they’re different.

### Testing Coverage

One can check how much of their package is covered by testing. The most common package to achieve this is the `covr` package. It should be compatible with any testing package, including `testthat` and `tinytest`. Testing coverage can be automated using Github Actions as such `usethis::use_github_action("test-coverage")` or can be run locally using `report()`.

## Deployment

### Shiny Apps

When considering developing an R Shiny App, you need to decide where the App can be accessed. The Scottish Government runs an R Shiny Server to deploy publicly facing apps. For those apps that are for internal use only there are a couple of options. One is to host the App on a Linux Server on the OSE. This method works, but does limit the accessibility to only OSE users, limiting it's usefulness. Another option is to run a Linux Server within a Docker container and run the Docker Container on a server accessible from both SCOTS and the OSE. A useful reference document to setting up a Linux Server can be found at https://docs.posit.co/shiny-server/.

### Docker

Docker is a program that allows you to manipulate (launch and stop) multiple operating systems (called containers) on your machine (your machine will be called the host). Docker is designed to enclose environments inside an image / a container. One of its main benefits when working with R is that it can alleviate any dependency issues. So from a reproducibility point of view it is very helpful, as well as helping to get round some of the issues with code sharing on the OSE and dependencies. Another use for Docker is the deployment of shiny Apps internally. One can set up a Linux server within the Docker container, and host the app from here.

To use Docker one must install Docker Desktop, this requires system admin privileges on the OSE. It is unclear whether this is feasible on SCOTS. The software requires a decent bit of space, so may be an issue when installing on the OSE where space is limited.

The Rocker project (https://rocker-project.org/) is an R for Docker project that has created a number of preset images for use with R. rocker/shiny and rocker/shiny-verse are preset Docker images for deploying Shiny apps, the only difference being that rocker/shiny-verse also has the `tidyverse` packages installed. Unfortunately it is not feasible to simply run rocker/shiny to deploy Shiny Apps without setting the proxy. Further details on how to set this up can be found here: https://rocker-project.org/use/networking.html.

### Github Actions

Github can also be used to automate deployment of both apps and packages, as well as running scripts or markdown documents. GitHub Actions are a way to get your code to run automatically on a virtual computer in the cloud that GitHub maintains. You can schedule when these run if you want to run a report every month or you can schedule the action to run on a trigger. There are essentially five steps to implementing Github Actions:

1. Tell the code when it should run
2. Start a virtual computer
3. Install R
4. Install all packages you need to run your code
5. Run your code

GitHub Actions works through YAML files placed in the .github/workflows directory. These YAML files contain a set of instructions that tell the virtual computer what to do.

It can be tricky to get your Github Actions working correctly, so there is a bit of a time sink, so this must be weighed up with the benefits. YAML files are notoriously finicky with regard to spacing. Each indentation is done with two spaces (not tabs).
